package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/coilyco/umbra/http/guardfile"
)

// flattenBanner marks the artifact as generated. A reader who opens the mounted
// file must not edit it, and the line names what to edit instead.
const flattenBanner = "// Generated by `mcp-beaver flatten`. Edit the source guardfile, not this file.\n"

// runFlatten resolves `inherit` into one document: the composed guardfile, not
// every file it names. A widget an `app` states rides in beside it. See
// docs/spec-mode.md.
func runFlatten(out io.Writer, argv []string) error {
	fs := flag.NewFlagSet("flatten", flag.ContinueOnError)
	dst := fs.String("o", "", "write the flattened guardfile here instead of stdout")
	check := fs.Bool("check", false, "verify -o already matches, writing nothing; exit non-zero on drift")
	if err := fs.Parse(reorderFlagsFirst(argv)); err != nil {
		return err
	}
	if fs.NArg() != 1 {
		return fmt.Errorf("flatten needs exactly one spec path, e.g. `flatten services/forgejo-mcp/forgejo.mcp.kdl`")
	}
	if *check && *dst == "" {
		return fmt.Errorf("flatten --check needs -o naming the committed artifact to compare against")
	}
	src := fs.Arg(0)

	flat, err := guardfile.Flatten(src)
	if err != nil {
		return fmt.Errorf("flatten %q: %w", src, err)
	}
	rendered := append([]byte(flattenBanner), flat...)

	if *dst == "" {
		_, err = out.Write(rendered)
		return err
	}
	if *check {
		return checkFlattened(src, *dst, rendered)
	}
	if err := os.WriteFile(*dst, rendered, 0o644); err != nil { //nolint:gosec // a reviewed policy artifact, not a secret
		return fmt.Errorf("write %q: %w", *dst, err)
	}
	return nil
}

// checkFlattened is the CI half: the committed artifact is what gets mounted,
// so a stale one silently serves a policy nobody reviewed. Scope is that file,
// so an edited widget leaves it green - see docs/spec-mode.md for why.
func checkFlattened(src, dst string, want []byte) error {
	got, err := os.ReadFile(dst) //nolint:gosec // operator-supplied trusted policy path
	if err != nil {
		return fmt.Errorf("read %q: %w (regenerate with `mcp-beaver flatten %s -o %s`)", dst, err, src, dst)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale against %s; regenerate with `mcp-beaver flatten %s -o %s`", dst, src, src, dst)
	}
	return nil
}
